### ISSUE TITLE
Fix influxdb format

### ISSUE THREAD

**Issue by PegasusPrime** [hawson/monitor-core#1]
In your "build_influxdb_line" function, the return method needs to return some kind of key/value pair for the value, not just the numerical value to adhere to the line protocol spec. 

Example fix (added value=): return apr_psprintf(pool, "%s,hostname=%s%s value=%s %lu",

**Comment by hawson** [comment]
Commit a6d8ef9b6f676efdf5aab2fb0ecd3f49dc1d9730
Added a new "measurement" option for each `collection_group`.  It is optional, so as to not interfere with existing configurations.  It is _strongly_ suggested that collection groups collect similar items, as all items in the group will have the same "measurement" value.  Multiple collection_groups can have the same value for "measurement".
