### ISSUE TITLE
[influxdb] Use built-in tags instead of "default_tags" option

### ISSUE THREAD

**Issue by satterly** [hawson/monitor-core#15]
Unless there is a very good reason, I would suggest that you use the existing `tags` gmond configuration option instead of requiring the user to define two sets of tags, one of which is specifically for influxdb.

**Comment by hawson** [comment]
You mean the apparently undocumented, mentioned only in source-code "tags" configuration option, global option?  Any idea on how much this is actually used on in the field?

**Comment by satterly** [comment]
They may seem undocumented but as you say they are right there in the code base. And yes they are used extensively in integrations with other tools like Riemann.

**Comment by satterly** [comment]
This fix assumes tags are always defined by the user in the influxdb config stanza.

**Comment by hawson** [comment]
Tags are valid in the global stanza, as before, and in the influxdb_channel
stanza, also as before.  The combination of the two will be used in the
influxdb message.

## 

Jesse Becker

**Comment by satterly** [comment]
I think that's a bad idea. But anyway, I was actually trying to explain that I think the code has a bug. It seems to me that you are assuming that a user will always configure influxdb tags if they add the influxdb config stanza because you are appending the global tags to the end of them. What if there are no influxdb tags to append to? Do you get a leading comma (",") and does that create an empty tag?
