### ISSUE TITLE
[influxdb] Replace "measurement" config option with "group"

### ISSUE THREAD

**Issue by satterly** [hawson/monitor-core#16]
> Every collection_group stanza may now have an optional "measurement" attribute. This attribute is used to assist InfluxDB in organizing metrics into groups of "measurements".  

Ganglia already supports grouping metrics using the "group" metadata attribute and it is used widely by all Ganglia metric modules. The influxdb integration should make use of this existing feature instead of creating something "influxdb-specific".

**Comment by hawson** [comment]
Can you point me to the documentation for the "group" metadata attribute, if any?  InfluxDB specifically needs something that is _named_, and so far as I can tell, none of the existing collection_group configuration 

...digging around a bit, I see the "GROUP" XML tag set by the modules, and not the core gmond code.  
I'll look into pulling that information.  Regardless, I'll leave the ability to override that setting, as the admin sees fit.

**Comment by satterly** [comment]
Metric groups are used in every C and Python module ever written for Ganglia.

**C examples**
https://github.com/ganglia/monitor-core/search?p=1&q=MGROUP&type=Code

**Python examples**
https://github.com/ganglia/gmond_python_modules/search?q=groups&type=Code

As you can see "groups" is used everywhere and so adding a configuration option like "measurement" is completely redundant and will only confuse users, new and old.

**Comment by hawson** [comment]
Fixed by 1e251bc9122f0dae6cd90ffbcc356b4524a18c86.  Follow ups in 97ec98c and e6a34a3.

**Comment by satterly** [comment]
What's the motivation behind e6a34a31718e9704c6901021423be4f174fed2e0 ?

**Comment by hawson** [comment]
Adjust groups from e6a34a3 with c562037.
