### ISSUE TITLE
[influxdb] Make gmond influxdb support configurable compile-time option

### ISSUE THREAD

**Issue by satterly** [hawson/monitor-core#17]
Support for influxdb in `gmond` should be a compile time option similar to `sFlow`. Whether it is enabled or disabled by default is a question that could be addressed later but it should be an option either way rather than hard-coded which is what it is currently.

**Comment by hawson** [comment]
Yeah, I considered that early in the process, but didn't for three reasons
1. I didn't want to mess with any of the automake/autoconf mess
2. The code is a noop if there are no stanzas defined
3. Littering the code with #IFDEFs is pretty ugly.  Even though I tried to minimized the number of changes to gmond, there are still far too many for my liking.  Wrapping them in #IFDEFs would make the code harder to read than it is already.
4. There shouldn't be an new dependencies (libraries, etc), which would warrent changes to the compile process.

That said, I do like the idea of a compile time option.

**Comment by satterly** [comment]
I completely agree that automake/autoconf is a mess -- I hate dealing with it. Considering that there are no dependencies and as you say if no outputs are configured then it's a "noop" then maybe it would be ok. FYI, Host sFlow support started as "opt in" now it's "opt out".
